name: Deploy Python project to Azure Function App - Direct Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.9'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: .python_packages
          key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Install dependencies
        run: |
          pip install --target=".python_packages/lib/site-packages" -r ./requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_465775D76CA5448BB6432ED8A34E4FF2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_08CFD732EBCA4ADA8778CD85AA2BC2ED }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F7F34C990DA54DA48DE2E38DB358BA8A }}
      
      - name: 'Deploy to Azure Function App'
        uses: Azure/functions-action@v1
        with:
          app-name: 'New-Gen-AI-Bot'
          package: '.'
          scm-do-build-during-deployment: false
